### ISSUE TITLE
CUDA OOM after one epoch

### ISSUE THREAD

**Issue by xtzd** [ikkyu-wen/huawei-garbage#12]
always CUDA OOM after one epoch... no matter how many batchsize is.. 4 GPU machine.

**Comment by xtzd** [comment]
File "/home/user-x/miniconda3/envs/torch1.0.1/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 11.91 GiB total capacity; 10.70 GiB already allocated; 2.88 MiB free; 11.18 GiB reserved in total by PyTorch)

**Comment by QLMX** [comment]
You can reduce the size of bs or the image size
