### ISSUE TITLE
about preprocess_img

### ISSUE THREAD

**Issue by zengwb-lx** [ikkyu-wen/huawei-garbage#13]
请问你的图像预处理是不是错了，没有做NCHW的转换
img = data['input_img']
img = img.unsqueeze(0)
img = img.to(self.device)
with torch.no_grad():
        pred_score = self.model(img)

**Comment by QLMX** [comment]
没有错的

zengwbz <notifications@github.com> 于2020年9月22日周二 下午10:36写道：
