### ISSUE TITLE
why index should add one in dataset.py?

### ISSUE THREAD

**Issue by backkon** [ikkyu-wen/huawei-garbage#14]
i want to know why index should add one ?

   def getitem(self, index):
        assert index <= len(self), 'index range error'
        **index += 1**
        img_path, label = self.env[index].strip().split(',')

        try:
            img = Image.open(img_path)
        except:
            print(img_path)
            print('Corrupted image for %d' % index)
            return self[index + 1]

        if self.transform is not None:
            if img.layers == 1:
                print(img_path)
            img = self.transform(img)

        if self.target_transform is not None:
            label = self.target_transform(label)
        return (img, int(label))

**Comment by QLMX** [comment]
Because the first line of my file is the header
