### ISSUE TITLE
针对类别少的参数调整

### ISSUE THREAD

**Issue by cancangit** [ikkyu-wen/huawei-garbage#19]
如果我只针对几个类别的垃圾图片进行训练，参数该怎么调整。对于较少类别的（我选的是4类）训练结果一直在36左右，提不上去

**Comment by QLMX** [comment]
直接改一下类别数量就行

cancangit <notifications@github.com> 于2020年11月26日周四 下午9:58写道：

**Comment by cancangit** [comment]
并不管用，因为我之前已经改了类别数，想着咨询下要不要改一些模型参数？

**Comment by QLMX** [comment]
你可以看看网络后面的全连接层

cancangit <notifications@github.com> 于2020年11月27日周五 下午9:58写道：

**Comment by cancangit** [comment]
嗯，感谢，我再多尝试尝试。
