### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by womeibing** [ikkyu-wen/huawei-garbage#22]
这个代码训练时使用TTA策略了吗？

**Comment by 5carecrow** [comment]
借楼请问一下，为什么类别是43个类，我看官网的数据集是40类

**Comment by QLMX** [comment]
复赛好像是43

Scrc <notifications@github.com> 于2020年12月18日周五 下午12:12写道：

**Comment by yulin01** [comment]
请问数据集在哪里下载呢？

**Comment by QLMX** [comment]
官网目前应该没有下载链接了，你只能在网上看看有人保存的吗
