### ISSUE TITLE
您好！请问你们训练了多少个epoch达到收敛了？

### ISSUE THREAD

**Issue by BCWang93** [ikkyu-wen/huawei-garbage#23]
您好！请问，你们训练了多少个epochs能够收敛，我看代码中epochs参数设置的是200貌似，然后好像也没看到你们使用early stopping。所以，想问下，你们训练了多少个epochs。

**Comment by Aarnnity** [comment]
> 您好！请问，你们训练了多少个epochs能够收敛，我看代码中epochs参数设置的是200貌似，然后好像也没看到你们使用early stopping。所以，想问下，你们训练了多少个epochs。
请问您还在torcs上训练DDPG么？不知道有关图像作为神经网络的输入是否已经解决了？想跟您交流一下。

**Comment by Aarnnity** [comment]
> 您好！请问，你们训练了多少个epochs能够收敛，我看代码中epochs参数设置的是200貌似，然后好像也没看到你们使用early stopping。所以，想问下，你们训练了多少个epochs。

请问您还在torcs上训练DDPG么？不知道有关图像作为神经网络的输入是否已经解决了？想跟您交流一下。

**Comment by QLMX** [comment]
我跑了大概20多个epoch就收敛了

发自我的iPhone
