### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by xubo-cyber** [ikkyu-wen/huawei-garbage#25]
大佬，您好，我是在idea中运行您的代码，但我没有通过requirement直接安装指定版本的包（有些包下载遇到问题），我手动安装了要求的包（版本较高）。
但是在utils.py中第50行中”StackNet“显示无法解析，我查了一下pytorch的开发手册，没有找到StackNet类。请问一下这是在哪个包里？

在radam.py文件中的第11行，”import required“，我去看了一下optimizer中的代码，没发现什么问题。我去掉requied后，文件中也没有报错，请问一下可以去掉这个required吗？

在customize_service.py文件中，要导入华为的包，我看PTServingBaseService没有在其他地方被引用，又在华为网站上发现好像在华为云上运行才需要写这个，我就注释掉了，这没关系吧？

**Comment by Anonymous-ace** [comment]
遇到了同样的问题，请问您解决了吗

**Comment by xubo-cyber** [comment]
抱歉，我还没试一下，还没解决



在 2021-03-05 11:19:47，"dong xx" <notifications@github.com> 写道：

遇到了同样的问题，请问您解决了吗

**Comment by snow-tyan** [comment]
@XUeA111 你没用Pytorch搭建过网络吧，这语法错误，应该是后期改类名时，super没改过来
