### ISSUE TITLE
谢谢博主的分享！但博主的训练步骤不够详细,我补充一下训练的详细流程，

### ISSUE THREAD

**Issue by QQ2737499951** [ikkyu-wen/huawei-garbage#3]
谢谢博主的分享！但博主的训练步骤不够详细,我补充一下训练的详细流程，

第一步，建立文件夹data，把garbage_classify全部解压缩到data下;
第二步， 修改‘garbage_classify_V3.json’为‘garbage_classify_rule.json’,运行preprocess.py，生成训练集和测试集 ;
第三步，单张显卡的话，修改arg.py 85行 parser.add_argument('--gpu-id', default='0, 1, 2, 3' 为'--gpu-id', default='0'，同时修改 '--train-batch'，'--test-batch'为适当的数字;
第四步，运行train.py

**### 数据集下载
**

[https://modelarts-competitions.obs.cn-north-1.myhuaweicloud.com/garbage_classify/dataset/garbage_classify.zip](https://modelarts-competitions.obs.cn-north-1.myhuaweicloud.com/garbage_classify/dataset/garbage_classify.zip)
 
本期包含了日常生活中收集的40种垃圾图像，每对数据包括TXT中的垃圾图像及其标签文件。图像名称及其对应的数字标签中一行的格式，例如“ image_0.jpg，0”（名称，标签）。数据索引不连续，图像总数约为14802。

垃圾种类40类
{
    "0": "其他垃圾/一次性快餐盒",
    "1": "其他垃圾/污损塑料",
    "2": "其他垃圾/烟蒂",
    "3": "其他垃圾/牙签",
    "4": "其他垃圾/破碎花盆及碟碗",
    "5": "其他垃圾/竹筷",
    "6": "厨余垃圾/剩饭剩菜",
    "7": "厨余垃圾/大骨头",
    "8": "厨余垃圾/水果果皮",
    "9": "厨余垃圾/水果果肉",
    "10": "厨余垃圾/茶叶渣",
    "11": "厨余垃圾/菜叶菜根",
    "12": "厨余垃圾/蛋壳",
    "13": "厨余垃圾/鱼骨",
    "14": "可回收物/充电宝",
    "15": "可回收物/包",
    "16": "可回收物/化妆品瓶",
    "17": "可回收物/塑料玩具",
    "18": "可回收物/塑料碗盆",
    "19": "可回收物/塑料衣架",
    "20": "可回收物/快递纸袋",
    "21": "可回收物/插头电线",
    "22": "可回收物/旧衣服",
    "23": "可回收物/易拉罐",
    "24": "可回收物/枕头",
    "25": "可回收物/毛绒玩具",
    "26": "可回收物/洗发水瓶",
    "27": "可回收物/玻璃杯",
    "28": "可回收物/皮鞋",
    "29": "可回收物/砧板",
    "30": "可回收物/纸板箱",
    "31": "可回收物/调料瓶",
    "32": "可回收物/酒瓶",
    "33": "可回收物/金属食品罐",
    "34": "可回收物/锅",
    "35": "可回收物/食用油桶",
    "36": "可回收物/饮料瓶",
    "37": "有害垃圾/干电池",
    "38": "有害垃圾/软膏",
    "39": "有害垃圾/过期药物"
}
 

全部代码结构（含原始数据集）

 
 {repo_root}
  ├── models	//模型文件夹
  ├── utils		//一些函数包
   |    ├── eval.py		// 求精度
  │    ├── misc.py		// 模型保存，参数初始化，优化函数选择
  │   ├── radam.py
  │   └── ...
  ├── args.py		//参数配置文件
  ├── build_net.py		//搭建模型
  ├── dataset.py		//数据批量加载文件
  ├── preprocess.py		//数据预处理文件，生成坐标标签
  ├── train.py		//训练运行文件
  ├── transform.py		//数据增强文件
  **├──data        //建立文件夹data，把garbage_classify全部解压缩到data下
   |     ├──garbage_classify
   |      |    ├──train_data            //全部训练数据集
   |      |    ├──garbage_classify_rule.json        //标签文件**

python版本为3.6，具体的函数包如下：

pytorch>=1.0.1
torchvision>=0.2.2
matplotlib>=3.1.0
numpy>=1.16.4
scikit-image
pandas
sklearn
adabound
requests

py3.7训练的话，要修改下面的代码
`        if use_cuda:
            inputs, targets = inputs.cuda(), targets.cuda(async=True)
        inputs, targets = torch.autograd.Variable(inputs), torch.autograd.Variable(targets)`
#python3.7已经移除了async关键字，而用non_blocking代替。(导致apache-airflow也出了问题)
#cuda() 本身也没有async.

就是把 async=True去掉

**if use_cuda:
                     inputs, targets = inputs.cuda(), targets.cuda()
        inputs, targets = torch.autograd.Variable(inputs), torch.autograd.Variable(targets)`**

**Comment by ikkyu-wen** [comment]
谢谢，我将你的步骤直接更新到READE中

**Comment by QLMX** [comment]
谢谢，我将你添加的步骤直接更新到readme中
