### ISSUE TITLE
ModuleNotFoundError: No module named 'adabound'

### ISSUE THREAD

**Issue by xiaohuaibaoguigui** [ikkyu-wen/huawei-garbage#6]
感谢您的分享！
训练时提示：
ModuleNotFoundError: No module named 'adabound'
adabound的实现是您自己写的吗？我可以从github找一个别的实现放在代码里吗？

**Comment by QLMX** [comment]
不是的，一个开源项目，可以直接pip安装

xiaohuaibaoguigui <notifications@github.com> 于2020年2月21日周五 下午10:10写道：
