### ISSUE TITLE
您好，测试集精度只有88左右，正常吗？

### ISSUE THREAD

**Issue by xiaohuaibaoguigui** [ikkyu-wen/huawei-garbage#7]
train_loss:0.075142, val_loss:0.576665, train_acc:97.635311, train_5:99.954958, val_acc:87.491548, val_5:98.174442

您好，程序可以正常运行，速度也很快。使用垃圾分类的数据集进行复现时，测试集的top1精度只有88左右。这个结果正常吗？

训练时的batchsize是24，测试的batchsize是2.谢谢~

**Comment by QLMX** [comment]
你是在什么数据集上跑的，样本分布如何？

xiaohuaibaoguigui <notifications@github.com> 于2020年2月22日周六 下午10:37写道：
